---
title: VA Webtest
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  songs:
    title: Songs
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event
    permalink: "/events/:title"
    location: ''
    gig_date: ''
    link: ''
    state: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: songs
  values:
    layout: song
    permalink: "/songs/:title"
    artwork_image: 
    audio_file: 
    album_title: ''
    artist_name: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
